# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 031a20086033bf8f436c3b49d4c651839f3cafd3b60cd6b64e6f156e21ebc55d027573732f2f8262c7fad76bfd36e7b64e94a8f0b98e0a3429b5bf0c5c60a8a7

test:
  secret_key_base: f7a91e79c447f909a2753e4126ed30070c0e83f4462112ec85693d7bbeabc4d80c0e15d35a63b3837ae84277ecda888a366bdbf37515fea8267b297fadc2aa71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
